#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# pyenv config
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
if which pyenv-virtualenv-init > /dev/null; then
  eval "$(pyenv virtualenv-init -)"
fi

# set environment variables
# ensure packages are only installed in an active virtual environment
export PIP_REQUIRE_VIRTUALENV=true
# enable colorized output for howdoi
export HOWDOI_COLORIZE=1

# pipx config
export PATH="$PATH:/Users/benranderson/.local/bin"

# aliases
alias git="/usr/local/bin/git"
alias gs="git switch"
alias gac="git add -A && git commit -m"
alias gpl="git pull"
alias gp="git push --follow-tags"
alias gp1="git push --set-upstream origin"
alias gnb="git switch -c"
alias gdb="git branch -D"
alias grm="git rebase master"
alias plo="pip list --outdated"
alias gfp="git fetch --prune"
alias work="./.work.sh"
alias update="./.update-tools.sh"
alias ifp='venv subseadesign
pip install keyring artifacts-keyring
pip config --site set global.extra-index-url https://pkgs.dev.azure.com/technipfmc-dev/SubseaDesign/_packaging/SubseaDesignFeed/pypi/simple/
pip install fastpipe
fastpipe -V'

# functions
venv() {
    # create virtual env $1, activate it and update pip version
    pyenv virtualenv "$1"
    pyenv local "$1"
    pip install -U pip
}

# initialise mcfly
eval "$(mcfly init zsh)"

# enable tab completion for Terraform commands
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
